apiVersion: v1
kind: Namespace
metadata:
  name: test
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy
  namespace: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-deploy
  template:
    metadata:
      labels:
        app: test-deploy
    spec:
      containers:
      - name: nginx
        image: nginx
---

apiVersion: dulguun-test.io.dulguun-test.io/v1alpha1
kind: DeploymentFreezer
metadata:
  name: test-deploy-test-2
  namespace: test
spec:
  deploymentName: test-deploy
  deploymentNamespace: test
  durationSeconds: 30
