# This rule is not used by the project k8s-builder itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over dulguun-test.io.dulguun-test.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-builder
    app.kubernetes.io/managed-by: kustomize
  name: deploymentfreezer-admin-role
rules:
- apiGroups:
  - dulguun-test.io.dulguun-test.io
  resources:
  - deploymentfreezers
  verbs:
  - '*'
- apiGroups:
  - dulguun-test.io.dulguun-test.io
  resources:
  - deploymentfreezers/status
  verbs:
  - get
