# This rule is not used by the project k8s-builder itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the dulguun-test.io.dulguun-test.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-builder
    app.kubernetes.io/managed-by: kustomize
  name: deploymentfreezer-editor-role
rules:
- apiGroups:
  - dulguun-test.io.dulguun-test.io
  resources:
  - deploymentfreezers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dulguun-test.io.dulguun-test.io
  resources:
  - deploymentfreezers/status
  verbs:
  - get
