# This rule is not used by the project k8s-builder itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to dulguun-test.io.dulguun-test.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-builder
    app.kubernetes.io/managed-by: kustomize
  name: deploymentfreezer-viewer-role
rules:
- apiGroups:
  - dulguun-test.io.dulguun-test.io
  resources:
  - deploymentfreezers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dulguun-test.io.dulguun-test.io
  resources:
  - deploymentfreezers/status
  verbs:
  - get
