name: Build and Generate Manifests

on:
  push:
  pull_request:

jobs:
  build-and-generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make

      - name: Generate manifests
        run: make manifests

      - name: Build and push image
        run: |
          make docker-build docker-push IMG=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/k8s-builder:${{ github.sha }}

      - name: Upload manifests as artifact
        uses: actions/upload-artifact@v3
        with:
          name: k8s-manifests
          path: config/manifests/*.yaml